ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
####FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/lumiseven_01/kibana:6.6.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
