ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
####FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/lumiseven_01/elasticsearch:6.6.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
