ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
####FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/lumiseven_01/logstash:6.6.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
